version: '3'
services:
  database:
    image: postgres:10.10
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=persistent-storage
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

volumes:
  postgres:

networks:
  rabbitmq_go_net:
    driver: bridge